apiVersion: v1
kind: Service
metadata:
  name: im-ss1-service
  namespace: default
spec:
  selector:
    app: im-ss1   # matches the pod template label in your deployment
  ports:
  - name: http
    port: 80
    targetPort: 8000               # your container's containerPort
    protocol: TCP
  type: ClusterIP