apiVersion: v1
kind: Service
metadata:
  name: im-ss1-service
  labels:
    app: im-ss1
spec:
  type: LoadBalancer
  selector:
    app: im-ss1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
